title: <p align="center"> Ishan Karve </p>
logo: /assets/img/Skipper2.png

description:
  <p align="center">
  <a href="https://github.com/ishankarve">GitHub</a>
  
  <br>   
  This is a work in progress. The more I learn, the less I know.
  <br>
  </p>



theme: jekyll-theme-minimal
